CREATE SEQUENCE "ETEST"."BATCH_JOB_EXECUTION_SEQ"
START WITH 1080
MINVALUE 0
MAXVALUE 9223372036854775807
NOCYCLE
CACHE 20
NOORDER;


CREATE SEQUENCE "ETEST"."BATCH_JOB_SEQ"
START WITH 940
MINVALUE 0
MAXVALUE 9223372036854775807
NOCYCLE
CACHE 20
NOORDER;


CREATE SEQUENCE "ETEST"."BATCH_STEP_EXECUTION_SEQ"
START WITH 940
MINVALUE 0
MAXVALUE 9223372036854775807
NOCYCLE
CACHE 20
NOORDER;


CREATE SEQUENCE "ETEST"."ERROR_SEQ"
START WITH 108
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE
CACHE 20
NOORDER;


CREATE SEQUENCE "ETEST"."FAQ_SEQUENCE"
START WITH 3
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE
CACHE 20
NOORDER;


CREATE SEQUENCE "ETEST"."HIT_STAT_SEQ"
START WITH 93
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE
CACHE 20
NOORDER;


CREATE SEQUENCE "ETEST"."INQUIRY_FILE_SEQUENCE"
START WITH 36
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE
CACHE 20
NOORDER;


CREATE SEQUENCE "ETEST"."INQUIRY_SEQUENCE"
START WITH 51
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE
CACHE 20
NOORDER;


CREATE SEQUENCE "ETEST"."NOTICE_SEQUENCE"
START WITH 3
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE
CACHE 20
NOORDER;


CREATE SEQUENCE "ETEST"."PART_SEQ"
START WITH 10
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE
CACHE 20
NOORDER;


CREATE TABLE "ETEST"."ARTICLE" (
	"ARTICLE_ID" NUMBER,
	"ARTICLE_URL" VARCHAR(32),
	"TITLE" VARCHAR(128),
	"CREATE_DATE" TIMESTAMP(6),
	"CREATOR_ID" VARCHAR(32),
	"DESCRIPTION" VARCHAR(10000),
	"IMG_SRC" VARCHAR(32),
	"SOURCE" VARCHAR(128)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."ARTICLE_BOOKMARK" (
	"USER_UUID" VARCHAR(36),
	"ARTICLE_ID" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."ARTICLE_UK_REL" (
	"ARTICLE_ID" NUMBER,
	"UK_ID" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."BATCH_JOB_EXECUTION" (
	"JOB_EXECUTION_ID" NUMBER(19),
	"VERSION" NUMBER(19),
	"JOB_INSTANCE_ID" NUMBER(19),
	"CREATE_TIME" TIMESTAMP(6),
	"START_TIME" TIMESTAMP(6) DEFAULT NULL,
	"END_TIME" TIMESTAMP(6) DEFAULT NULL,
	"STATUS" VARCHAR(10 CHAR),
	"EXIT_CODE" VARCHAR(2500 CHAR),
	"EXIT_MESSAGE" VARCHAR(2500 CHAR),
	"LAST_UPDATED" TIMESTAMP(6),
	"JOB_CONFIGURATION_LOCATION" VARCHAR(2500 CHAR)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."BATCH_JOB_EXECUTION_CONTEXT" (
	"JOB_EXECUTION_ID" NUMBER(19),
	"SHORT_CONTEXT" VARCHAR(2500 CHAR),
	"SERIALIZED_CONTEXT" CLOB
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
LOB (SERIALIZED_CONTEXT) STORE AS ETEST_LOB1864700
	( TABLESPACE USR ENABLE STORAGE IN ROW )
NOPARALLEL;


CREATE TABLE "ETEST"."BATCH_JOB_EXECUTION_PARAMS" (
	"JOB_EXECUTION_ID" NUMBER(19),
	"TYPE_CD" VARCHAR(6 CHAR),
	"KEY_NAME" VARCHAR(100 CHAR),
	"STRING_VAL" VARCHAR(250 CHAR),
	"DATE_VAL" TIMESTAMP(6) DEFAULT NULL,
	"LONG_VAL" NUMBER(19),
	"DOUBLE_VAL" NUMBER,
	"IDENTIFYING" CHAR(1)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."BATCH_JOB_INSTANCE" (
	"JOB_INSTANCE_ID" NUMBER(19),
	"VERSION" NUMBER(19),
	"JOB_NAME" VARCHAR(100 CHAR),
	"JOB_KEY" VARCHAR(32 CHAR)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."BATCH_STEP_EXECUTION" (
	"STEP_EXECUTION_ID" NUMBER(19),
	"VERSION" NUMBER(19),
	"STEP_NAME" VARCHAR(100 CHAR),
	"JOB_EXECUTION_ID" NUMBER(19),
	"START_TIME" TIMESTAMP(6),
	"END_TIME" TIMESTAMP(6) DEFAULT NULL,
	"STATUS" VARCHAR(10 CHAR),
	"COMMIT_COUNT" NUMBER(19),
	"READ_COUNT" NUMBER(19),
	"FILTER_COUNT" NUMBER(19),
	"WRITE_COUNT" NUMBER(19),
	"READ_SKIP_COUNT" NUMBER(19),
	"WRITE_SKIP_COUNT" NUMBER(19),
	"PROCESS_SKIP_COUNT" NUMBER(19),
	"ROLLBACK_COUNT" NUMBER(19),
	"EXIT_CODE" VARCHAR(2500 CHAR),
	"EXIT_MESSAGE" VARCHAR(2500 CHAR),
	"LAST_UPDATED" TIMESTAMP(6)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."BATCH_STEP_EXECUTION_CONTEXT" (
	"STEP_EXECUTION_ID" NUMBER(19),
	"SHORT_CONTEXT" VARCHAR(2500 CHAR),
	"SERIALIZED_CONTEXT" CLOB
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
LOB (SERIALIZED_CONTEXT) STORE AS ETEST_LOB1864300
	( TABLESPACE USR ENABLE STORAGE IN ROW )
NOPARALLEL;


CREATE TABLE "ETEST"."BOOK" (
	"BOOK_ID" NUMBER,
	"BOOK_SRC" VARCHAR(32),
	"TITLE" VARCHAR(128),
	"CREATE_DATE" TIMESTAMP(6),
	"IMG_SRC" VARCHAR(32),
	"DESCRIPTION" VARCHAR(1024),
	"CODE_SET" VARCHAR(512),
	"CREATOR_ID" VARCHAR(128)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."BOOK_BOOKMARK" (
	"USER_UUID" VARCHAR(36),
	"BOOK_ID" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."BOOK_HIT" (
	"BOOK_ID" NUMBER,
	"HIT" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."CS_FAQ" (
	"FAQ_ID" NUMBER,
	"FAQ_TITLE" VARCHAR(100),
	"FAQ_CONTENT" VARCHAR(1000)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."CS_INQUIRY" (
	"INQUIRY_ID" NUMBER,
	"INQUIRY_STATUS" VARCHAR(100),
	"INQUIRY_TITLE" VARCHAR(100),
	"INQUIRY_TYPE" VARCHAR(100),
	"INQUIRY_CONTENT" VARCHAR(100),
	"INQUIRY_URL" VARCHAR(512),
	"INQUIRY_ANSWER" VARCHAR(2048),
	"USER_UUID" VARCHAR(36),
	"CREATE_DATE" TIMESTAMP(6),
	"INQUIRY_ANSWER_TIME" TIMESTAMP(6),
	"ADMIN_UUID" VARCHAR(36)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."CS_INQUIRY_FILE" (
	"INQUIRY_FILE_ID" NUMBER,
	"INQUIRY_FILE_URL" VARCHAR(100),
	"INQUIRY_FILE_TYPE" VARCHAR(100),
	"INQUIRY_ID" NUMBER,
	"INQUIRY_FILE_SIZE" NUMBER,
	"INQUIRY_FILE_NAME" VARCHAR(255)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."CS_NOTICE" (
	"NOTICE_ID" NUMBER,
	"NOTICE_TITLE" VARCHAR(100),
	"NOTICE_DATE" TIMESTAMP(6),
	"NOTICE_CONTENT" VARCHAR(2048)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."CURRICULUM_MASTER" (
	"CURRICULUM_ID" VARCHAR(255 CHAR),
	"CHAPTER" VARCHAR(255 CHAR),
	"CHAPTER_ID" VARCHAR(255 CHAR),
	"CURRICULUM_SEQUENCE" NUMBER(10),
	"GRADE" VARCHAR(255 CHAR),
	"SCHOOL_TYPE" VARCHAR(255 CHAR),
	"SECTION" VARCHAR(255 CHAR),
	"SEMESTER" VARCHAR(255 CHAR),
	"SUB_SECTION" VARCHAR(255 CHAR)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."DIAGNOSIS_CURRICULUM" (
	"CURRICULUM_ID" NUMBER,
	"CHAPTER" VARCHAR(100),
	"SECTION" VARCHAR(100),
	"SUB_SECTION" VARCHAR(100),
	"SUBJECT" VARCHAR(100),
	"SET_TYPE" CHAR(1),
	"STATUS" VARCHAR(20)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."DIAGNOSIS_PROBLEM" (
	"PROB_ID" NUMBER,
	"CURRICULUM_ID" NUMBER,
	"ORDER_NUM" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;
COMMENT ON TABLE "ETEST"."DIAGNOSIS_PROBLEM" IS '문제와 이미지 파일 경로의 상관 관계를 저장';
COMMENT ON COLUMN "ETEST"."DIAGNOSIS_PROBLEM"."PROB_ID" IS '문제 ID';
COMMENT ON COLUMN "ETEST"."DIAGNOSIS_PROBLEM"."CURRICULUM_ID" IS '분류 체계 ID (임시로 커리큘럼에)';
COMMENT ON COLUMN "ETEST"."DIAGNOSIS_PROBLEM"."ORDER_NUM" IS '문제 순서';


CREATE TABLE "ETEST"."DIAGNOSIS_REPORT" (
	"DIAGNOSIS_ID" VARCHAR(36),
	"USER_UUID" VARCHAR(50),
	"GI_SCORE" NUMBER,
	"RISK_SCORE" NUMBER,
	"RISK_PROFILE_SCORE" NUMBER,
	"RISK_TRACING_SCORE" NUMBER,
	"RISK_LEVEL_SCORE" NUMBER,
	"RISK_CAPA_SCORE" NUMBER,
	"INVEST_SCORE" NUMBER,
	"INVEST_PROFILE_SCORE" NUMBER,
	"INVEST_TRACING_SCORE" NUMBER,
	"KNOWLEDGE_SCORE" NUMBER,
	"KNOWLEDGE_COMMON_SCORE" NUMBER,
	"KNOWLEDGE_TYPE_SCORE" NUMBER,
	"KNOWLEDGE_CHANGE_SCORE" NUMBER,
	"KNOWLEDGE_SELL_SCORE" NUMBER,
	"AVG_UK_MASTERY" NUMBER,
	"USER_MBTI" VARCHAR(5),
	"INVEST_PERIOD" NUMBER, 
	"INVEST_ITEM_NUM" NUMBER,
	"STOCK_RATIO" NUMBER,
	"DIAGNOSIS_DATE" TIMESTAMP(6),
	"RECOMMEND_BASIC_LIST" VARCHAR(500),
	"RECOMMEND_TYPE_LIST" VARCHAR(500),
	"RECOMMEND_ADVANCED_LIST" VARCHAR(500)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."ERROR_REPORT" (
	"ERROR_ID" NUMBER,
	"PROB_ID" NUMBER,
	"USER_UUID" VARCHAR(36),
	"REPORT_TYPE" VARCHAR(32),
	"REPORT_TEXT" VARCHAR(1024)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."HASHTAG" (
	"HASHTAG_ID" NUMBER,
	"NAME" VARCHAR(128)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."HIT_STAT" (
	"STAT_DATE" DATE,
	"HIT_STAT_ID" NUMBER,
	"VIDEO_HIT" NUMBER,
	"BOOK_HIT" NUMBER,
	"WIKI_HIT" NUMBER,
	"ARTICLE_HIT" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."META_CODE_MASTER" (
	"META_CODE_ID" VARCHAR(32),
	"DOMAIN" VARCHAR(100),
	"SEQUENCE" NUMBER,
	"CODE" VARCHAR(100),
	"CODE_NAME" VARCHAR(256)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."MINITEST_REPORT" (
	"MINITEST_ID" VARCHAR(36),
	"USER_UUID" VARCHAR(36),
	"AVG_UK_MASTERY" NUMBER,
	"SET_NUM" NUMBER,
	"CORRECT_NUM" NUMBER,
	"WRONG_NUM" NUMBER,
	"DUNNO_NUM" NUMBER,
	"MINITEST_DATE" TIMESTAMP(6),
	"MINITEST_UK_MASTERY" VARCHAR(3000)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."PART" (
	"PART_ID" NUMBER,
	"PART_NAME" VARCHAR(100),
	"ORDER_NUM" NUMBER,
	"PROBLEM_COUNT" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."PROBLEM" (
	"PROB_ID" NUMBER,
	"ANSWER_TYPE" VARCHAR(50),
	"QUESTION" VARCHAR(40000),
	"SOLUTION" VARCHAR(40000),
	"DIFFICULTY" VARCHAR(20),
	"CATEGORY" VARCHAR(20),
	"IMG_SRC" VARCHAR(256),
	"TIME_RECOMMENDATION" NUMBER,
	"CREATOR_ID" VARCHAR(32),
	"CREATE_DATE" TIMESTAMP(6),
	"VALIDATOR_ID" VARCHAR(32),
	"VALIDATE_DATE" TIMESTAMP(6),
	"EDITOR_ID" VARCHAR(32),
	"EDIT_DATE" TIMESTAMP(6),
	"SOURCE" VARCHAR(512),
	"INTENTION" VARCHAR(100),
	"QUESTION_INITIAL" VARCHAR(40000),
	"SOLUTION_INITIAL" VARCHAR(40000)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;
COMMENT ON TABLE "ETEST"."PROBLEM" IS '문제 내용을 저장';
COMMENT ON COLUMN "ETEST"."PROBLEM"."PROB_ID" IS '문제 ID';
COMMENT ON COLUMN "ETEST"."PROBLEM"."ANSWER_TYPE" IS '답안 유형';
COMMENT ON COLUMN "ETEST"."PROBLEM"."QUESTION" IS '질문';
COMMENT ON COLUMN "ETEST"."PROBLEM"."SOLUTION" IS '해설';
COMMENT ON COLUMN "ETEST"."PROBLEM"."DIFFICULTY" IS '문제 난이도';
COMMENT ON COLUMN "ETEST"."PROBLEM"."CATEGORY" IS '분류';
COMMENT ON COLUMN "ETEST"."PROBLEM"."IMG_SRC" IS '이미지 경로';
COMMENT ON COLUMN "ETEST"."PROBLEM"."TIME_RECOMMENDATION" IS '적정 풀이 시간';
COMMENT ON COLUMN "ETEST"."PROBLEM"."CREATOR_ID" IS '생성자';
COMMENT ON COLUMN "ETEST"."PROBLEM"."CREATE_DATE" IS '생성 날짜';
COMMENT ON COLUMN "ETEST"."PROBLEM"."VALIDATOR_ID" IS '검수자';
COMMENT ON COLUMN "ETEST"."PROBLEM"."VALIDATE_DATE" IS '검수 날짜';
COMMENT ON COLUMN "ETEST"."PROBLEM"."EDITOR_ID" IS '수정자';
COMMENT ON COLUMN "ETEST"."PROBLEM"."EDIT_DATE" IS '수정 날짜';
COMMENT ON COLUMN "ETEST"."PROBLEM"."SOURCE" IS '문제 출처';
COMMENT ON COLUMN "ETEST"."PROBLEM"."INTENTION" IS '출제 의도';
COMMENT ON COLUMN "ETEST"."PROBLEM"."QUESTION_INITIAL" IS '질문 초성';
COMMENT ON COLUMN "ETEST"."PROBLEM"."SOLUTION_INITIAL" IS '해설 초성';


CREATE TABLE "ETEST"."PROBLEM_CHOICE" (
	"PROB_ID" NUMBER,
	"CHOICE_NUM" NUMBER,
	"UK_ID" NUMBER,
	"CHOICE_SCORE" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;
COMMENT ON TABLE "ETEST"."PROBLEM_CHOICE" IS '문제와 이미지 파일 경로의 상관 관계를 저장';
COMMENT ON COLUMN "ETEST"."PROBLEM_CHOICE"."PROB_ID" IS '문제 ID';
COMMENT ON COLUMN "ETEST"."PROBLEM_CHOICE"."CHOICE_NUM" IS '문제 보기 번호';
COMMENT ON COLUMN "ETEST"."PROBLEM_CHOICE"."UK_ID" IS 'UK_ID';


CREATE TABLE "ETEST"."PROBLEM_UK_REL" (
	"PROB_ID" NUMBER,
	"UK_ID" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;
COMMENT ON TABLE "ETEST"."PROBLEM_UK_REL" IS '문제와 지식 추적 UK의 상관 관계를 저장';
COMMENT ON COLUMN "ETEST"."PROBLEM_UK_REL"."PROB_ID" IS '문제 ID';
COMMENT ON COLUMN "ETEST"."PROBLEM_UK_REL"."UK_ID" IS 'UK_ID';


CREATE TABLE "ETEST"."STATEMENT" (
	"STATEMENT_ID" VARCHAR(100),
	"USER_ID" VARCHAR(100),
	"ACTION_TYPE" VARCHAR(100),
	"SOURCE_TYPE" VARCHAR(100),
	"SOURCE_ID" VARCHAR(100),
	"TIMESTAMP" VARCHAR(100),
	"PLATFORM" VARCHAR(100),
	"CURSOR_TIME" NUMBER,
	"IS_CORRECT" NUMBER,
	"IS_DELETED" NUMBER,
	"USER_ANSWER" VARCHAR(500),
	"DURATION" VARCHAR(100),
	"EXTENSION" VARCHAR(2000),
	"STATEMENT_DATE" TIMESTAMP(6)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."TEST_PROBLEM" (
	"PROB_ID" NUMBER,
	"PART_ID" NUMBER,
	"SUBJECT" VARCHAR(100),
	"STATUS" VARCHAR(20)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;
COMMENT ON TABLE "ETEST"."TEST_PROBLEM" IS '문제와 이미지 파일 경로의 상관 관계를 저장';
COMMENT ON COLUMN "ETEST"."TEST_PROBLEM"."PROB_ID" IS '문제 ID';


CREATE TABLE "ETEST"."UK_MASTER" (
	"UK_ID" NUMBER,
	"UK_NAME" VARCHAR(200),
	"UK_DESCRIPTION" VARCHAR(1000),
	"TRAIN_UNSEEN" CHAR(1),
	"CURRICULUM_ID" VARCHAR(255 CHAR),
	"PART" VARCHAR(50),
	"EXTERNAL_LINK" VARCHAR(2000)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."UK_REL" (
	"BASE_UK_ID" NUMBER,
	"PRE_UK_ID" NUMBER,
	"RELATION_REFERENCE" VARCHAR(32)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."USER_EMBEDDING" (
	"USER_UUID" VARCHAR(255 CHAR),
	"UPDATE_DATE" TIMESTAMP(6),
	"USER_EMBEDDING" VARCHAR(255 CHAR)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."USER_KNOWLEDGE" (
	"USER_UUID" VARCHAR(36),
	"UK_MASTERY" NUMBER,
	"UPDATE_DATE" TIMESTAMP(6),
	"UK_ID" VARCHAR(255 CHAR)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."USER_MASTER" (
	"USER_UUID" VARCHAR(36),
	"USER_TYPE" VARCHAR(100),
	"EMAIL" VARCHAR(100) DEFAULT 'test@test.com',
	"GENDER" VARCHAR(100) DEFAULT 'male',
	"PROVIDER" VARCHAR(100) DEFAULT 'naver',
	"ROLE" VARCHAR(100) DEFAULT 'USER',
	"BIRTHDAY" TIMESTAMP(6) DEFAULT '2021-03-03',
	"COLLECT_INFO" VARCHAR(10) DEFAULT '0',
	"SERVICE_AGREEMENT" VARCHAR(10) DEFAULT '1',
	"OLDER_THAN_14" VARCHAR(10) DEFAULT '1',
	"ACCOUNT_ACTIVE" VARCHAR(10) DEFAULT '1',
	"EVENT_SMS_AGREEMENT" VARCHAR(10) DEFAULT '1',
	"PROVIDER_ID" VARCHAR(1000) DEFAULT '1234',
	"CREATE_DATE" TIMESTAMP(6),
	"NICK_NAME" VARCHAR(200) DEFAULT '-',
	"NAME" VARCHAR(100)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."VIDEO" (
	"VIDEO_ID" VARCHAR(32),
	"VIDEO_SRC" VARCHAR(256),
	"ORIGINAL_FILE_SRC" VARCHAR(256),
	"TITLE" VARCHAR(512),
	"IMG_SRC" VARCHAR(32),
	"CURRICULUM_ID" NUMBER,
	"TOTAL_TIME" NUMBER,
	"START_TIME" NUMBER,
	"END_TIME" NUMBER,
	"CREATE_DATE" DATE,
	"REGISTER_DATE" DATE,
	"END_DATE" DATE,
	"SEQUENCE" NUMBER,
	"CODE_SET" VARCHAR(512)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."VIDEO_BOOKMARK" (
	"USER_UUID" VARCHAR(36),
	"VIDEO_ID" VARCHAR(32)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."VIDEO_CURRICULUM" (
	"CURRICULUM_ID" NUMBER,
	"SUBJECT" VARCHAR(128)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."VIDEO_HASHTAG" (
	"HASHTAG_ID" NUMBER,
	"VIDEO_ID" VARCHAR(32)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."VIDEO_HIT" (
	"HIT" NUMBER,
	"VIDEO_ID" VARCHAR(32)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."VIDEO_UK_REL" (
	"UK_ID" NUMBER,
	"VIDEO_ID" VARCHAR(32)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."WIKI" (
	"WIKI_ID" NUMBER,
	"TITLE" VARCHAR(128),
	"CREATE_DATE" TIMESTAMP(6),
	"CREATOR_ID" VARCHAR(32),
	"DESCRIPTION" VARCHAR(10000),
	"SUMMARY" VARCHAR(256),
	"SOURCE" VARCHAR(128)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."WIKI_BOOKMARK" (
	"USER_UUID" VARCHAR(36),
	"WIKI_ID" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE TABLE "ETEST"."WIKI_UK_REL" (
	"WIKI_ID" NUMBER,
	"UK_ID" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX "ETEST"."ETEST_CON1282100128" ON "ETEST"."CURRICULUM_MASTER" (
	"CURRICULUM_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."ETEST_CON1287100143" ON "ETEST"."DIAGNOSIS_CURRICULUM" (
	"CURRICULUM_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."ETEST_CON1290000468" ON "ETEST"."USER_EMBEDDING" (
	"USER_UUID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."ETEST_CON1302000673" ON "ETEST"."TEST_PROBLEM" (
	"PROB_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."ETEST_CON1305500873" ON "ETEST"."HASHTAG" (
	"HASHTAG_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."ETEST_CON1306400760" ON "ETEST"."PROBLEM_CHOICE" (
	"PROB_ID" ASC,
	"CHOICE_NUM" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."ETEST_CON1308600903" ON "ETEST"."HIT_STAT" (
	"STAT_DATE" ASC,
	"HIT_STAT_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."ETEST_CON1310400051" ON "ETEST"."BATCH_JOB_INSTANCE" (
	"JOB_INSTANCE_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."ETEST_CON1310900784" ON "ETEST"."BATCH_JOB_EXECUTION" (
	"JOB_EXECUTION_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."ETEST_CON1311900252" ON "ETEST"."BATCH_STEP_EXECUTION" (
	"STEP_EXECUTION_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."ETEST_CON1312600476" ON "ETEST"."BATCH_STEP_EXECUTION_CONTEXT" (
	"STEP_EXECUTION_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."ETEST_CON1313000184" ON "ETEST"."BATCH_JOB_EXECUTION_CONTEXT" (
	"JOB_EXECUTION_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."ETEST_CON1314800322" ON "ETEST"."META_CODE_MASTER" (
	"META_CODE_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."ETEST_CON1316500348" ON "ETEST"."BOOK_HIT" (
	"BOOK_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."ETEST_CON1318100934" ON "ETEST"."VIDEO" (
	"VIDEO_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."ETEST_CON1319900934" ON "ETEST"."VIDEO_BOOKMARK" (
	"USER_UUID" ASC,
	"VIDEO_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."ETEST_CON1320900473" ON "ETEST"."DIAGNOSIS_REPORT" (
	"DIAGNOSIS_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."JOB_INST_UN" ON "ETEST"."BATCH_JOB_INSTANCE" (
	"JOB_NAME" ASC,
	"JOB_KEY" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_ARTICLE" ON "ETEST"."ARTICLE" (
	"ARTICLE_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_ARTICLE_BOOKMARK" ON "ETEST"."ARTICLE_BOOKMARK" (
	"USER_UUID" ASC,
	"ARTICLE_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_ARTICLE_UK_REL" ON "ETEST"."ARTICLE_UK_REL" (
	"ARTICLE_ID" ASC,
	"UK_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_BOOK" ON "ETEST"."BOOK" (
	"BOOK_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_BOOK_BOOKMARK" ON "ETEST"."BOOK_BOOKMARK" (
	"USER_UUID" ASC,
	"BOOK_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_DIAGNOSIS_PROBLEM" ON "ETEST"."DIAGNOSIS_PROBLEM" (
	"PROB_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_ERROR_REPORT" ON "ETEST"."ERROR_REPORT" (
	"ERROR_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_FAQ_ID" ON "ETEST"."CS_FAQ" (
	"FAQ_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_INQUIRY_ID" ON "ETEST"."CS_INQUIRY" (
	"INQUIRY_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_MINITEST_REPORT" ON "ETEST"."MINITEST_REPORT" (
	"MINITEST_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_NOTICE_ID" ON "ETEST"."CS_NOTICE" (
	"NOTICE_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_PART" ON "ETEST"."PART" (
	"PART_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_PROBLEM" ON "ETEST"."PROBLEM" (
	"PROB_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_STATEMENT_MASTER" ON "ETEST"."STATEMENT" (
	"STATEMENT_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_UK_MASTER" ON "ETEST"."UK_MASTER" (
	"UK_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_USER_KNOWLEDGE" ON "ETEST"."USER_KNOWLEDGE" (
	"USER_UUID" ASC,
	"UK_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_USER_MASTER" ON "ETEST"."USER_MASTER" (
	"USER_UUID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_VIDEO_CURRICULUM" ON "ETEST"."VIDEO_CURRICULUM" (
	"CURRICULUM_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_WIKI" ON "ETEST"."WIKI" (
	"WIKI_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_WIKI_BOOKMARK" ON "ETEST"."WIKI_BOOKMARK" (
	"USER_UUID" ASC,
	"WIKI_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "ETEST"."PK_WIKI_UK_REL" ON "ETEST"."WIKI_UK_REL" (
	"WIKI_ID" ASC,
	"UK_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


ALTER TABLE "ETEST"."USER_MASTER" MODIFY 	"USER_UUID" NOT NULL;


ALTER TABLE "ETEST"."UK_MASTER" MODIFY 	"UK_ID" NOT NULL;


ALTER TABLE "ETEST"."UK_MASTER" MODIFY 	"UK_NAME" NOT NULL;


ALTER TABLE "ETEST"."UK_MASTER" MODIFY 	"TRAIN_UNSEEN" NOT NULL;


ALTER TABLE "ETEST"."PROBLEM" MODIFY 	"PROB_ID" NOT NULL;


ALTER TABLE "ETEST"."PROBLEM" MODIFY 	"ANSWER_TYPE" NOT NULL;


ALTER TABLE "ETEST"."PROBLEM" MODIFY 	"QUESTION" NOT NULL;


ALTER TABLE "ETEST"."PROBLEM" MODIFY 	"SOLUTION" NOT NULL;


ALTER TABLE "ETEST"."USER_KNOWLEDGE" MODIFY 	"USER_UUID" NOT NULL;


ALTER TABLE "ETEST"."UK_REL" MODIFY 	"BASE_UK_ID" NOT NULL;


ALTER TABLE "ETEST"."UK_REL" MODIFY 	"PRE_UK_ID" NOT NULL;


ALTER TABLE "ETEST"."TEST_PROBLEM" MODIFY 	"PROB_ID" NOT NULL;


ALTER TABLE "ETEST"."PROBLEM_UK_REL" MODIFY 	"PROB_ID" NOT NULL;


ALTER TABLE "ETEST"."PROBLEM_UK_REL" MODIFY 	"UK_ID" NOT NULL;


ALTER TABLE "ETEST"."PROBLEM_CHOICE" MODIFY 	"PROB_ID" NOT NULL;


ALTER TABLE "ETEST"."PROBLEM_CHOICE" MODIFY 	"CHOICE_NUM" NOT NULL;


ALTER TABLE "ETEST"."CURRICULUM_MASTER" MODIFY 	"CURRICULUM_ID" NOT NULL;


ALTER TABLE "ETEST"."CURRICULUM_MASTER" ADD
PRIMARY KEY (
	"CURRICULUM_ID"
);


ALTER TABLE "ETEST"."USER_KNOWLEDGE" MODIFY 	"UK_ID" NOT NULL;


ALTER TABLE "ETEST"."ERROR_REPORT" MODIFY 	"ERROR_ID" NOT NULL;


ALTER TABLE "ETEST"."ERROR_REPORT" MODIFY 	"PROB_ID" NOT NULL;


ALTER TABLE "ETEST"."ERROR_REPORT" MODIFY 	"USER_UUID" NOT NULL;


ALTER TABLE "ETEST"."ERROR_REPORT" MODIFY 	"REPORT_TYPE" NOT NULL;


ALTER TABLE "ETEST"."DIAGNOSIS_CURRICULUM" MODIFY 	"CURRICULUM_ID" NOT NULL;


ALTER TABLE "ETEST"."DIAGNOSIS_CURRICULUM" MODIFY 	"CHAPTER" NOT NULL;


ALTER TABLE "ETEST"."DIAGNOSIS_CURRICULUM" ADD
PRIMARY KEY (
	"CURRICULUM_ID"
);


ALTER TABLE "ETEST"."DIAGNOSIS_PROBLEM" MODIFY 	"PROB_ID" NOT NULL;


ALTER TABLE "ETEST"."DIAGNOSIS_PROBLEM" MODIFY 	"CURRICULUM_ID" NOT NULL;


ALTER TABLE "ETEST"."USER_EMBEDDING" MODIFY 	"USER_UUID" NOT NULL;


ALTER TABLE "ETEST"."USER_EMBEDDING" ADD
PRIMARY KEY (
	"USER_UUID"
);


ALTER TABLE "ETEST"."ARTICLE" MODIFY 	"ARTICLE_ID" NOT NULL;


ALTER TABLE "ETEST"."ARTICLE" MODIFY 	"ARTICLE_URL" NOT NULL;


ALTER TABLE "ETEST"."ARTICLE" MODIFY 	"TITLE" NOT NULL;


ALTER TABLE "ETEST"."ARTICLE" MODIFY 	"CREATE_DATE" NOT NULL;


ALTER TABLE "ETEST"."ARTICLE" MODIFY 	"CREATOR_ID" NOT NULL;


ALTER TABLE "ETEST"."ARTICLE" MODIFY 	"DESCRIPTION" NOT NULL;


ALTER TABLE "ETEST"."ARTICLE" MODIFY 	"IMG_SRC" NOT NULL;


ALTER TABLE "ETEST"."WIKI" MODIFY 	"WIKI_ID" NOT NULL;


ALTER TABLE "ETEST"."WIKI" MODIFY 	"TITLE" NOT NULL;


ALTER TABLE "ETEST"."WIKI" MODIFY 	"CREATE_DATE" NOT NULL;


ALTER TABLE "ETEST"."WIKI" MODIFY 	"CREATOR_ID" NOT NULL;


ALTER TABLE "ETEST"."WIKI" MODIFY 	"DESCRIPTION" NOT NULL;


ALTER TABLE "ETEST"."WIKI" MODIFY 	"SUMMARY" NOT NULL;


ALTER TABLE "ETEST"."BOOK" MODIFY 	"BOOK_ID" NOT NULL;


ALTER TABLE "ETEST"."BOOK" MODIFY 	"BOOK_SRC" NOT NULL;


ALTER TABLE "ETEST"."BOOK" MODIFY 	"TITLE" NOT NULL;


ALTER TABLE "ETEST"."BOOK" MODIFY 	"CREATE_DATE" NOT NULL;


ALTER TABLE "ETEST"."BOOK" MODIFY 	"IMG_SRC" NOT NULL;


ALTER TABLE "ETEST"."BOOK" MODIFY 	"DESCRIPTION" NOT NULL;


ALTER TABLE "ETEST"."ARTICLE_BOOKMARK" MODIFY 	"USER_UUID" NOT NULL;


ALTER TABLE "ETEST"."ARTICLE_BOOKMARK" MODIFY 	"ARTICLE_ID" NOT NULL;


ALTER TABLE "ETEST"."WIKI_BOOKMARK" MODIFY 	"USER_UUID" NOT NULL;


ALTER TABLE "ETEST"."WIKI_BOOKMARK" MODIFY 	"WIKI_ID" NOT NULL;


ALTER TABLE "ETEST"."BOOK_BOOKMARK" MODIFY 	"USER_UUID" NOT NULL;


ALTER TABLE "ETEST"."BOOK_BOOKMARK" MODIFY 	"BOOK_ID" NOT NULL;


ALTER TABLE "ETEST"."ARTICLE_UK_REL" MODIFY 	"ARTICLE_ID" NOT NULL;


ALTER TABLE "ETEST"."ARTICLE_UK_REL" MODIFY 	"UK_ID" NOT NULL;


ALTER TABLE "ETEST"."WIKI_UK_REL" MODIFY 	"WIKI_ID" NOT NULL;


ALTER TABLE "ETEST"."WIKI_UK_REL" MODIFY 	"UK_ID" NOT NULL;


ALTER TABLE "ETEST"."VIDEO_UK_REL" MODIFY 	"UK_ID" NOT NULL;


ALTER TABLE "ETEST"."VIDEO_BOOKMARK" MODIFY 	"USER_UUID" NOT NULL;


ALTER TABLE "ETEST"."VIDEO_CURRICULUM" MODIFY 	"CURRICULUM_ID" NOT NULL;


ALTER TABLE "ETEST"."VIDEO_CURRICULUM" MODIFY 	"SUBJECT" NOT NULL;


ALTER TABLE "ETEST"."VIDEO_HIT" MODIFY 	"HIT" NOT NULL;


ALTER TABLE "ETEST"."DIAGNOSIS_CURRICULUM" MODIFY 	"SECTION" NOT NULL;


ALTER TABLE "ETEST"."DIAGNOSIS_CURRICULUM" MODIFY 	"SUB_SECTION" NOT NULL;


ALTER TABLE "ETEST"."DIAGNOSIS_CURRICULUM" MODIFY 	"STATUS" NOT NULL;


ALTER TABLE "ETEST"."PART" MODIFY 	"PART_ID" NOT NULL;


ALTER TABLE "ETEST"."PART" MODIFY 	"PART_NAME" NOT NULL;


ALTER TABLE "ETEST"."PART" MODIFY 	"ORDER_NUM" NOT NULL;


ALTER TABLE "ETEST"."PART" MODIFY 	"PROBLEM_COUNT" NOT NULL;


ALTER TABLE "ETEST"."TEST_PROBLEM" MODIFY 	"STATUS" NOT NULL;


ALTER TABLE "ETEST"."TEST_PROBLEM" ADD
PRIMARY KEY (
	"PROB_ID"
);


ALTER TABLE "ETEST"."USER_MASTER" MODIFY 	"EMAIL" NOT NULL;


ALTER TABLE "ETEST"."USER_MASTER" MODIFY 	"GENDER" NOT NULL;


ALTER TABLE "ETEST"."USER_MASTER" MODIFY 	"PROVIDER" NOT NULL;


ALTER TABLE "ETEST"."USER_MASTER" MODIFY 	"ROLE" NOT NULL;


ALTER TABLE "ETEST"."USER_MASTER" MODIFY 	"BIRTHDAY" NOT NULL;


ALTER TABLE "ETEST"."USER_MASTER" MODIFY 	"COLLECT_INFO" NOT NULL;


ALTER TABLE "ETEST"."USER_MASTER" MODIFY 	"SERVICE_AGREEMENT" NOT NULL;


ALTER TABLE "ETEST"."USER_MASTER" MODIFY 	"OLDER_THAN_14" NOT NULL;


ALTER TABLE "ETEST"."USER_MASTER" MODIFY 	"ACCOUNT_ACTIVE" NOT NULL;


ALTER TABLE "ETEST"."USER_MASTER" MODIFY 	"EVENT_SMS_AGREEMENT" NOT NULL;


ALTER TABLE "ETEST"."USER_MASTER" MODIFY 	"PROVIDER_ID" NOT NULL;


ALTER TABLE "ETEST"."CS_INQUIRY" MODIFY 	"INQUIRY_ID" NOT NULL;


ALTER TABLE "ETEST"."CS_NOTICE" MODIFY 	"NOTICE_ID" NOT NULL;


ALTER TABLE "ETEST"."CS_FAQ" MODIFY 	"FAQ_ID" NOT NULL;


ALTER TABLE "ETEST"."CS_INQUIRY" MODIFY 	"USER_UUID" NOT NULL;


ALTER TABLE "ETEST"."CS_INQUIRY_FILE" MODIFY 	"INQUIRY_FILE_ID" NOT NULL;


ALTER TABLE "ETEST"."CS_INQUIRY_FILE" MODIFY 	"INQUIRY_FILE_URL" NOT NULL;


ALTER TABLE "ETEST"."HASHTAG" MODIFY 	"HASHTAG_ID" NOT NULL;


ALTER TABLE "ETEST"."HASHTAG" ADD
PRIMARY KEY (
	"HASHTAG_ID"
);


ALTER TABLE "ETEST"."VIDEO_HASHTAG" MODIFY 	"HASHTAG_ID" NOT NULL;


ALTER TABLE "ETEST"."PROBLEM_CHOICE" ADD
PRIMARY KEY (
	"PROB_ID",
	"CHOICE_NUM"
);


ALTER TABLE "ETEST"."USER_MASTER" MODIFY 	"NICK_NAME" NOT NULL;


ALTER TABLE "ETEST"."DIAGNOSIS_REPORT" MODIFY 	"DIAGNOSIS_ID" NOT NULL;


ALTER TABLE "ETEST"."DIAGNOSIS_REPORT" MODIFY 	"USER_UUID" NOT NULL;


ALTER TABLE "ETEST"."DIAGNOSIS_REPORT" MODIFY 	"DIAGNOSIS_DATE" NOT NULL;


ALTER TABLE "ETEST"."HIT_STAT" MODIFY 	"STAT_DATE" NOT NULL;


ALTER TABLE "ETEST"."HIT_STAT" MODIFY 	"HIT_STAT_ID" NOT NULL;


ALTER TABLE "ETEST"."HIT_STAT" ADD
PRIMARY KEY (
	"STAT_DATE",
	"HIT_STAT_ID"
);


ALTER TABLE "ETEST"."STATEMENT" MODIFY 	"STATEMENT_ID" NOT NULL;


ALTER TABLE "ETEST"."STATEMENT" MODIFY 	"USER_ID" NOT NULL;


ALTER TABLE "ETEST"."STATEMENT" MODIFY 	"ACTION_TYPE" NOT NULL;


ALTER TABLE "ETEST"."STATEMENT" MODIFY 	"SOURCE_TYPE" NOT NULL;


ALTER TABLE "ETEST"."STATEMENT" MODIFY 	"TIMESTAMP" NOT NULL;


ALTER TABLE "ETEST"."BATCH_JOB_INSTANCE" MODIFY 	"JOB_INSTANCE_ID" NOT NULL;


ALTER TABLE "ETEST"."BATCH_JOB_INSTANCE" ADD
PRIMARY KEY (
	"JOB_INSTANCE_ID"
);


ALTER TABLE "ETEST"."BATCH_JOB_INSTANCE" MODIFY 	"JOB_NAME" NOT NULL;


ALTER TABLE "ETEST"."BATCH_JOB_INSTANCE" MODIFY 	"JOB_KEY" NOT NULL;


ALTER TABLE "ETEST"."BATCH_JOB_EXECUTION" MODIFY 	"JOB_EXECUTION_ID" NOT NULL;


ALTER TABLE "ETEST"."BATCH_JOB_EXECUTION" ADD
PRIMARY KEY (
	"JOB_EXECUTION_ID"
);


ALTER TABLE "ETEST"."BATCH_JOB_EXECUTION" MODIFY 	"JOB_INSTANCE_ID" NOT NULL;


ALTER TABLE "ETEST"."BATCH_JOB_EXECUTION" MODIFY 	"CREATE_TIME" NOT NULL;


ALTER TABLE "ETEST"."BATCH_JOB_EXECUTION_PARAMS" MODIFY 	"JOB_EXECUTION_ID" NOT NULL;


ALTER TABLE "ETEST"."BATCH_JOB_EXECUTION_PARAMS" MODIFY 	"TYPE_CD" NOT NULL;


ALTER TABLE "ETEST"."BATCH_JOB_EXECUTION_PARAMS" MODIFY 	"KEY_NAME" NOT NULL;


ALTER TABLE "ETEST"."BATCH_JOB_EXECUTION_PARAMS" MODIFY 	"IDENTIFYING" NOT NULL;


ALTER TABLE "ETEST"."BATCH_STEP_EXECUTION" MODIFY 	"STEP_EXECUTION_ID" NOT NULL;


ALTER TABLE "ETEST"."BATCH_STEP_EXECUTION" ADD
PRIMARY KEY (
	"STEP_EXECUTION_ID"
);


ALTER TABLE "ETEST"."BATCH_STEP_EXECUTION" MODIFY 	"VERSION" NOT NULL;


ALTER TABLE "ETEST"."BATCH_STEP_EXECUTION" MODIFY 	"STEP_NAME" NOT NULL;


ALTER TABLE "ETEST"."BATCH_STEP_EXECUTION" MODIFY 	"JOB_EXECUTION_ID" NOT NULL;


ALTER TABLE "ETEST"."BATCH_STEP_EXECUTION" MODIFY 	"START_TIME" NOT NULL;


ALTER TABLE "ETEST"."BATCH_STEP_EXECUTION_CONTEXT" MODIFY 	"STEP_EXECUTION_ID" NOT NULL;


ALTER TABLE "ETEST"."BATCH_STEP_EXECUTION_CONTEXT" ADD
PRIMARY KEY (
	"STEP_EXECUTION_ID"
);


ALTER TABLE "ETEST"."BATCH_STEP_EXECUTION_CONTEXT" MODIFY 	"SHORT_CONTEXT" NOT NULL;


ALTER TABLE "ETEST"."BATCH_JOB_EXECUTION_CONTEXT" MODIFY 	"JOB_EXECUTION_ID" NOT NULL;


ALTER TABLE "ETEST"."BATCH_JOB_EXECUTION_CONTEXT" ADD
PRIMARY KEY (
	"JOB_EXECUTION_ID"
);


ALTER TABLE "ETEST"."BATCH_JOB_EXECUTION_CONTEXT" MODIFY 	"SHORT_CONTEXT" NOT NULL;


ALTER TABLE "ETEST"."MINITEST_REPORT" MODIFY 	"MINITEST_ID" NOT NULL;


ALTER TABLE "ETEST"."MINITEST_REPORT" MODIFY 	"USER_UUID" NOT NULL;


ALTER TABLE "ETEST"."MINITEST_REPORT" MODIFY 	"AVG_UK_MASTERY" NOT NULL;


ALTER TABLE "ETEST"."MINITEST_REPORT" MODIFY 	"SET_NUM" NOT NULL;


ALTER TABLE "ETEST"."MINITEST_REPORT" MODIFY 	"MINITEST_DATE" NOT NULL;


ALTER TABLE "ETEST"."META_CODE_MASTER" MODIFY 	"META_CODE_ID" NOT NULL;


ALTER TABLE "ETEST"."META_CODE_MASTER" MODIFY 	"DOMAIN" NOT NULL;


ALTER TABLE "ETEST"."META_CODE_MASTER" MODIFY 	"CODE" NOT NULL;


ALTER TABLE "ETEST"."META_CODE_MASTER" MODIFY 	"CODE_NAME" NOT NULL;


ALTER TABLE "ETEST"."META_CODE_MASTER" ADD
PRIMARY KEY (
	"META_CODE_ID"
);


ALTER TABLE "ETEST"."BOOK_HIT" MODIFY 	"BOOK_ID" NOT NULL;


ALTER TABLE "ETEST"."BOOK_HIT" MODIFY 	"HIT" NOT NULL;


ALTER TABLE "ETEST"."BOOK_HIT" ADD
PRIMARY KEY (
	"BOOK_ID"
);


ALTER TABLE "ETEST"."VIDEO" MODIFY 	"VIDEO_ID" NOT NULL;


ALTER TABLE "ETEST"."VIDEO" MODIFY 	"VIDEO_SRC" NOT NULL;


ALTER TABLE "ETEST"."VIDEO" MODIFY 	"TITLE" NOT NULL;


ALTER TABLE "ETEST"."VIDEO" MODIFY 	"IMG_SRC" NOT NULL;


ALTER TABLE "ETEST"."VIDEO" MODIFY 	"CURRICULUM_ID" NOT NULL;


ALTER TABLE "ETEST"."VIDEO" MODIFY 	"TOTAL_TIME" NOT NULL;


ALTER TABLE "ETEST"."VIDEO" MODIFY 	"SEQUENCE" NOT NULL;


ALTER TABLE "ETEST"."VIDEO" ADD
PRIMARY KEY (
	"VIDEO_ID"
);


ALTER TABLE "ETEST"."VIDEO_BOOKMARK" ADD
PRIMARY KEY (
	"USER_UUID",
	"VIDEO_ID"
);


ALTER TABLE "ETEST"."DIAGNOSIS_REPORT" ADD
PRIMARY KEY (
	"DIAGNOSIS_ID"
);


ALTER TABLE "ETEST"."BATCH_JOB_INSTANCE" ADD CONSTRAINT "JOB_INST_UN"
UNIQUE (
	"JOB_NAME",
	"JOB_KEY"
);


ALTER TABLE "ETEST"."ARTICLE" ADD CONSTRAINT "PK_ARTICLE"
PRIMARY KEY (
	"ARTICLE_ID"
);


ALTER TABLE "ETEST"."ARTICLE_BOOKMARK" ADD CONSTRAINT "PK_ARTICLE_BOOKMARK"
PRIMARY KEY (
	"USER_UUID",
	"ARTICLE_ID"
);


ALTER TABLE "ETEST"."ARTICLE_UK_REL" ADD CONSTRAINT "PK_ARTICLE_UK_REL"
PRIMARY KEY (
	"ARTICLE_ID",
	"UK_ID"
);


ALTER TABLE "ETEST"."BOOK" ADD CONSTRAINT "PK_BOOK"
PRIMARY KEY (
	"BOOK_ID"
);


ALTER TABLE "ETEST"."BOOK_BOOKMARK" ADD CONSTRAINT "PK_BOOK_BOOKMARK"
PRIMARY KEY (
	"USER_UUID",
	"BOOK_ID"
);


ALTER TABLE "ETEST"."DIAGNOSIS_PROBLEM" ADD CONSTRAINT "PK_DIAGNOSIS_PROBLEM"
PRIMARY KEY (
	"PROB_ID"
);


ALTER TABLE "ETEST"."ERROR_REPORT" ADD CONSTRAINT "PK_ERROR_REPORT"
PRIMARY KEY (
	"ERROR_ID"
);


ALTER TABLE "ETEST"."CS_FAQ" ADD CONSTRAINT "PK_FAQ_ID"
PRIMARY KEY (
	"FAQ_ID"
);


ALTER TABLE "ETEST"."CS_INQUIRY" ADD CONSTRAINT "PK_INQUIRY_ID"
PRIMARY KEY (
	"INQUIRY_ID"
);


ALTER TABLE "ETEST"."MINITEST_REPORT" ADD CONSTRAINT "PK_MINITEST_REPORT"
PRIMARY KEY (
	"MINITEST_ID"
);


ALTER TABLE "ETEST"."CS_NOTICE" ADD CONSTRAINT "PK_NOTICE_ID"
PRIMARY KEY (
	"NOTICE_ID"
);


ALTER TABLE "ETEST"."PART" ADD CONSTRAINT "PK_PART"
PRIMARY KEY (
	"PART_ID"
);


ALTER TABLE "ETEST"."PROBLEM" ADD CONSTRAINT "PK_PROBLEM"
PRIMARY KEY (
	"PROB_ID"
);


ALTER TABLE "ETEST"."STATEMENT" ADD CONSTRAINT "PK_STATEMENT_MASTER"
PRIMARY KEY (
	"STATEMENT_ID"
);


ALTER TABLE "ETEST"."UK_MASTER" ADD CONSTRAINT "PK_UK_MASTER"
PRIMARY KEY (
	"UK_ID"
);


ALTER TABLE "ETEST"."USER_KNOWLEDGE" ADD CONSTRAINT "PK_USER_KNOWLEDGE"
PRIMARY KEY (
	"USER_UUID",
	"UK_ID"
);


ALTER TABLE "ETEST"."USER_MASTER" ADD CONSTRAINT "PK_USER_MASTER"
PRIMARY KEY (
	"USER_UUID"
);


ALTER TABLE "ETEST"."VIDEO_CURRICULUM" ADD CONSTRAINT "PK_VIDEO_CURRICULUM"
PRIMARY KEY (
	"CURRICULUM_ID"
);


ALTER TABLE "ETEST"."WIKI" ADD CONSTRAINT "PK_WIKI"
PRIMARY KEY (
	"WIKI_ID"
);


ALTER TABLE "ETEST"."WIKI_BOOKMARK" ADD CONSTRAINT "PK_WIKI_BOOKMARK"
PRIMARY KEY (
	"USER_UUID",
	"WIKI_ID"
);


ALTER TABLE "ETEST"."WIKI_UK_REL" ADD CONSTRAINT "PK_WIKI_UK_REL"
PRIMARY KEY (
	"WIKI_ID",
	"UK_ID"
);


ALTER TABLE "ETEST"."ARTICLE_UK_REL" ADD CONSTRAINT "ARTICLE_UK_REL_UK_MASTER_UK_ID_FK"
FOREIGN KEY (
	"UK_ID"
) REFERENCES "ETEST"."UK_MASTER" (
	"UK_ID"
);


ALTER TABLE "ETEST"."ARTICLE_BOOKMARK" ADD CONSTRAINT "FK_ARTICLE_BOOKMARK_ARTICLE_ID"
FOREIGN KEY (
	"ARTICLE_ID"
) REFERENCES "ETEST"."ARTICLE" (
	"ARTICLE_ID"
);


ALTER TABLE "ETEST"."ARTICLE_BOOKMARK" ADD CONSTRAINT "FK_ARTICLE_BOOKMARK_USER_UUID_"
FOREIGN KEY (
	"USER_UUID"
) REFERENCES "ETEST"."USER_MASTER" (
	"USER_UUID"
);


ALTER TABLE "ETEST"."ARTICLE_UK_REL" ADD CONSTRAINT "FK_ARTICLE_UK_REL_ARTICLE_ID_A"
FOREIGN KEY (
	"ARTICLE_ID"
) REFERENCES "ETEST"."ARTICLE" (
	"ARTICLE_ID"
);


ALTER TABLE "ETEST"."BOOK_BOOKMARK" ADD CONSTRAINT "FK_BOOK_BOOKMARK_BOOK_ID_BOOK_"
FOREIGN KEY (
	"BOOK_ID"
) REFERENCES "ETEST"."BOOK" (
	"BOOK_ID"
);


ALTER TABLE "ETEST"."BOOK_BOOKMARK" ADD CONSTRAINT "FK_BOOK_BOOKMARK_USER_UUID_USE"
FOREIGN KEY (
	"USER_UUID"
) REFERENCES "ETEST"."USER_MASTER" (
	"USER_UUID"
);


ALTER TABLE "ETEST"."BOOK_HIT" ADD CONSTRAINT "FK_BOOK_HIT_BOOK_ID_BOOK_BOOK_"
FOREIGN KEY (
	"BOOK_ID"
) REFERENCES "ETEST"."BOOK" (
	"BOOK_ID"
);


ALTER TABLE "ETEST"."DIAGNOSIS_PROBLEM" ADD CONSTRAINT "FK_DIAGNOSIS_PROBLEM_CURRICULUM_ID"
FOREIGN KEY (
	"CURRICULUM_ID"
) REFERENCES "ETEST"."DIAGNOSIS_CURRICULUM" (
	"CURRICULUM_ID"
);


ALTER TABLE "ETEST"."DIAGNOSIS_PROBLEM" ADD CONSTRAINT "FK_DIAGNOSIS_PROBLEM_PROB_ID"
FOREIGN KEY (
	"PROB_ID"
) REFERENCES "ETEST"."PROBLEM" (
	"PROB_ID"
);


ALTER TABLE "ETEST"."ERROR_REPORT" ADD CONSTRAINT "FK_ERROR_REPORT_USER_UUID_USER"
FOREIGN KEY (
	"USER_UUID"
) REFERENCES "ETEST"."USER_MASTER" (
	"USER_UUID"
);


ALTER TABLE "ETEST"."PROBLEM_CHOICE" ADD CONSTRAINT "FK_PROBLEM_CHOICE_PROB_ID"
FOREIGN KEY (
	"PROB_ID"
) REFERENCES "ETEST"."PROBLEM" (
	"PROB_ID"
);


ALTER TABLE "ETEST"."PROBLEM_UK_REL" ADD CONSTRAINT "FK_PROBLEM_UK_REL_PROB_ID"
FOREIGN KEY (
	"PROB_ID"
) REFERENCES "ETEST"."PROBLEM" (
	"PROB_ID"
);


ALTER TABLE "ETEST"."TEST_PROBLEM" ADD CONSTRAINT "FK_TEST_PROBLEM_PART_ID"
FOREIGN KEY (
	"PART_ID"
) REFERENCES "ETEST"."PART" (
	"PART_ID"
);


ALTER TABLE "ETEST"."TEST_PROBLEM" ADD CONSTRAINT "FK_TEST_PROBLEM_PROB_ID"
FOREIGN KEY (
	"PROB_ID"
) REFERENCES "ETEST"."PROBLEM" (
	"PROB_ID"
);


ALTER TABLE "ETEST"."USER_KNOWLEDGE" ADD CONSTRAINT "FK_USER_KNOWLEDGE_USER_UUID_US"
FOREIGN KEY (
	"USER_UUID"
) REFERENCES "ETEST"."USER_MASTER" (
	"USER_UUID"
);


ALTER TABLE "ETEST"."VIDEO_BOOKMARK" ADD CONSTRAINT "FK_VIDEO_BOOKMARK_USER_UUID_US"
FOREIGN KEY (
	"USER_UUID"
) REFERENCES "ETEST"."USER_MASTER" (
	"USER_UUID"
);


ALTER TABLE "ETEST"."VIDEO_BOOKMARK" ADD CONSTRAINT "FK_VIDEO_BOOKMARK_VIDEO_ID_VID"
FOREIGN KEY (
	"VIDEO_ID"
) REFERENCES "ETEST"."VIDEO" (
	"VIDEO_ID"
);


ALTER TABLE "ETEST"."VIDEO_HASHTAG" ADD CONSTRAINT "FK_VIDEO_HASHTAG_HASHTAG_ID_HA"
FOREIGN KEY (
	"HASHTAG_ID"
) REFERENCES "ETEST"."HASHTAG" (
	"HASHTAG_ID"
);


ALTER TABLE "ETEST"."VIDEO_HASHTAG" ADD CONSTRAINT "FK_VIDEO_HASHTAG_VIDEO_ID_VIDE"
FOREIGN KEY (
	"VIDEO_ID"
) REFERENCES "ETEST"."VIDEO" (
	"VIDEO_ID"
);


ALTER TABLE "ETEST"."VIDEO_HIT" ADD CONSTRAINT "FK_VIDEO_HIT_VIDEO_ID_VIDEO_VI"
FOREIGN KEY (
	"VIDEO_ID"
) REFERENCES "ETEST"."VIDEO" (
	"VIDEO_ID"
);


ALTER TABLE "ETEST"."WIKI_BOOKMARK" ADD CONSTRAINT "FK_WIKI_BOOKMARK_USER_UUID_USE"
FOREIGN KEY (
	"USER_UUID"
) REFERENCES "ETEST"."USER_MASTER" (
	"USER_UUID"
);


ALTER TABLE "ETEST"."WIKI_BOOKMARK" ADD CONSTRAINT "FK_WIKI_BOOKMARK_WIKI_ID_WIKI_"
FOREIGN KEY (
	"WIKI_ID"
) REFERENCES "ETEST"."WIKI" (
	"WIKI_ID"
);


ALTER TABLE "ETEST"."WIKI_UK_REL" ADD CONSTRAINT "FK_WIKI_UK_REL_WIKI_ID_WIKI_WI"
FOREIGN KEY (
	"WIKI_ID"
) REFERENCES "ETEST"."WIKI" (
	"WIKI_ID"
);


ALTER TABLE "ETEST"."BATCH_JOB_EXECUTION_CONTEXT" ADD CONSTRAINT "JOB_EXEC_CTX_FK"
FOREIGN KEY (
	"JOB_EXECUTION_ID"
) REFERENCES "ETEST"."BATCH_JOB_EXECUTION" (
	"JOB_EXECUTION_ID"
);


ALTER TABLE "ETEST"."BATCH_JOB_EXECUTION_PARAMS" ADD CONSTRAINT "JOB_EXEC_PARAMS_FK"
FOREIGN KEY (
	"JOB_EXECUTION_ID"
) REFERENCES "ETEST"."BATCH_JOB_EXECUTION" (
	"JOB_EXECUTION_ID"
);


ALTER TABLE "ETEST"."BATCH_STEP_EXECUTION" ADD CONSTRAINT "JOB_EXEC_STEP_FK"
FOREIGN KEY (
	"JOB_EXECUTION_ID"
) REFERENCES "ETEST"."BATCH_JOB_EXECUTION" (
	"JOB_EXECUTION_ID"
);


ALTER TABLE "ETEST"."BATCH_JOB_EXECUTION" ADD CONSTRAINT "JOB_INST_EXEC_FK"
FOREIGN KEY (
	"JOB_INSTANCE_ID"
) REFERENCES "ETEST"."BATCH_JOB_INSTANCE" (
	"JOB_INSTANCE_ID"
);


ALTER TABLE "ETEST"."PROBLEM_UK_REL" ADD CONSTRAINT "PROBLEM_UK_REL_UK_MASTER_UK_ID_FK"
FOREIGN KEY (
	"UK_ID"
) REFERENCES "ETEST"."UK_MASTER" (
	"UK_ID"
);


ALTER TABLE "ETEST"."BATCH_STEP_EXECUTION_CONTEXT" ADD CONSTRAINT "STEP_EXEC_CTX_FK"
FOREIGN KEY (
	"STEP_EXECUTION_ID"
) REFERENCES "ETEST"."BATCH_STEP_EXECUTION" (
	"STEP_EXECUTION_ID"
);


ALTER TABLE "ETEST"."UK_REL" ADD CONSTRAINT "UK_REL_BASE_UK_MASTER_UK_ID_FK"
FOREIGN KEY (
	"BASE_UK_ID"
) REFERENCES "ETEST"."UK_MASTER" (
	"UK_ID"
);


ALTER TABLE "ETEST"."UK_REL" ADD CONSTRAINT "UK_REL_PRE_UK_MASTER_UK_ID_FK"
FOREIGN KEY (
	"PRE_UK_ID"
) REFERENCES "ETEST"."UK_MASTER" (
	"UK_ID"
);


ALTER TABLE "ETEST"."VIDEO_UK_REL" ADD CONSTRAINT "VIDEO_UK_REL_UK_MASTER_UK_ID_FK"
FOREIGN KEY (
	"UK_ID"
) REFERENCES "ETEST"."UK_MASTER" (
	"UK_ID"
);


ALTER TABLE "ETEST"."VIDEO_UK_REL" ADD CONSTRAINT "VIDEO_UK_REL_VIDEO_VIDEO_ID_FK"
FOREIGN KEY (
	"VIDEO_ID"
) REFERENCES "ETEST"."VIDEO" (
	"VIDEO_ID"
);


ALTER TABLE "ETEST"."WIKI_UK_REL" ADD CONSTRAINT "WIKI_UK_REL_UK_MASTER_UK_ID_FK"
FOREIGN KEY (
	"UK_ID"
) REFERENCES "ETEST"."UK_MASTER" (
	"UK_ID"
);


