etest:
    recommend:
        lrs:
            host: 192.168.153.132
            port: 8080
        masterytriton:
            host: 192.168.153.209
            modelname: kt-rule
            modelver: 1
            port: 18000
restTemplate:
    factory:
        connectTimeout: 3000
        readTimeout: 5000
    httpClient:
        maxConnPerRoute: 5
        maxConnTotal: 100
server:
    port: 8080
spring:
    datasource:
        data: classpath:data.sql
        driver-class-name: com.tmax.tibero.jdbc.TbDriver
        initialization-mode: never
        password: etest
        schema: classpath:schema.sql
        sql-script-encoding: UTF-8
        url: jdbc:tibero:thin:@192.168.153.143:8629:tibero
        username: etest
    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
        generate-ddl: false
        properties:
            hibernate:

                jdbc:
                    batch_size: 32
        show-sql: true

