etest:
    recommend:
        lrs:
            host: 192.168.153.132
            port: 8080
        masterytriton:
            host: 192.168.153.209
            modelname: kt-rule
            modelver: 1
            port: 18000
restTemplate:
    factory:
        connectTimeout: 3000
        readTimeout: 5000
    httpClient:
        maxConnPerRoute: 5
        maxConnTotal: 100
server:
    port: 8080
spring:
    datasource:
        data: classpath:data.sql
        driver-class-name: com.tmax.tibero.jdbc.TbDriver
        initialization-mode: never
        password: etest
        schema: classpath:schema.sql
        sql-script-encoding: UTF-8
        url: jdbc:tibero:thin:@192.168.153.194:8629:tibero
        username: etest
    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
        generate-ddl: false
        properties:
            hibernate:

                jdbc:
                    batch_size: 32
        show-sql: true
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 405137734465-10a8s6r09kqn8b2tuehinvqqav5roa55.apps.googleusercontent.com
                        client-secret: mnpMTw3zxqVCVo-5BQAqgV4u
                        scope:
                            - email
                            - profile

                    facebook:
                        client-id: 184494353207222
                        client-secret: a56d23db48b45ba2645d23b003fb4460
                        scope:
                            - email
                            - public_profile

                    naver:
                        client-id: lAHlmFvbMzsST2AnArkd
                        client-secret: v102o4LjzR
                        scope:
                            - email
                        authorization-grant-type: authorization_code
                        redirect-uri: http://localhost:8080/login/oauth2/code/naver
                        client-name: Naver

                    kakao:
                        client-id:  1b5d2b5bc12d10c90759168fbba3eb8d
                        client-secret: E9JVKof67KVk6d829ltv8ENvN2UtP9QF
                        scope:
                            - account_email
                        authorization-grant-type: authorization_code
                        redirect-uri: http://localhost:8080/login/oauth2/code/kakao
                        client-name: Kakao
                        client-authentication-method: POST

                provider:
                    naver:
                        authorization-uri:  https://nid.naver.com/oauth2.0/authorize
                        token-uri:  https://nid.naver.com/oauth2.0/token
                        user-info-uri:  https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response

                    kakao:
                        authorization-uri:  https://kauth.kakao.com/oauth/authorize
                        token-uri:  https://kauth.kakao.com/oauth/token
                        user-info-uri:  https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id

#custom:
#    oauth2:
#        kakao:
#            client-id: 88a081241234cfacbedef7018ac451316f3
#            client-secret: jpXULoEzrasfawegsqYXlRLyyOHn2i60q
#        naver:
#            client-id: lAHlmFvbMzsST2AnArkd
#            client-secret: v102o4LjzR
