etest:
    recommend:
        lrs:
            host: 192.168.153.132
            port: 8080
        masterytriton:
            host: 192.168.153.209
            modelname: kt-rule
            modelver: 1
            port: 18000
restTemplate:
    factory:
        connectTimeout: 3000
        readTimeout: 5000
    httpClient:
        maxConnPerRoute: 5
        maxConnTotal: 100
server:
    port: 8080
spring:
    datasource:
        data: classpath:data.sql
        driver-class-name: com.tmax.tibero.jdbc.TbDriver
        initialization-mode: never
        password: etest
        schema: classpath:schema.sql
        sql-script-encoding: UTF-8
        url: jdbc:tibero:thin:@192.168.153.194:8629:tibero
        username: etest
    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
        generate-ddl: false
        properties:
            hibernate:
                jdbc:
                    batch_size: 32
        show-sql: true
    security:
        oauth2:
            client:
                registration:
                    facebook:
                        client-id: 276951674204554
                        client-secret: 11c56056f75c390f4bd945a512e13d7e
                        scope:
                            - public_profile
                            - email
        user:
            name: test
            password: 1234
springdoc:
    api-docs:
        path: /api-docs
