swagger: '2.0'
info:
  description: This is an API for test studio.
  version: 1.0.0
  title: test studio API
  contact:
    email: changeon_lim@tmax.co.kr
paths:
  /DiagProblems:
    get:
      tags:
      - teststudio
      summary: get diagProblems
      description:  
        자가진단 문제를 가져옵니다.
      # requestBody:
      #   description: 자가진단 문제를 가져옵니다.
      #   required: true
      #   content:
      #     application/json: 
      #       schema:
      #         $ref: '#/definitions/GetProblemDTOIn'
      parameters:
      - in: body
        # name: body
        # description: part
        required: true
        schema:
              $ref: '#/definitions/GetProblemDTOIn'
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/GetDiagProblemDTOOut'
        400:
          description: bad input parameter

    put:
      tags:
      - teststudio
      summary: update diagProblems
      description:  
        자가진단 문제를 수정합니다.
      parameters:
      - in: body
        required: true
        schema:
              $ref: '#/definitions/PutDiagProblemDTOIn'
      responses:
        200:
          description: success
        400:
          description: bad input parameter

          #  -----------------------------------------------------def  #a1

definitions:
  GetProblemDTOIn:
    type: object
    required:
    - userID
    - probID
    properties:
      userID:
        type: string
        example: 'userIDSample'
      probID:
        type: array
        example: [1,2,3]
        items:
          type: number
        
  GetDiagProblemDTOOut:
    type: object
    properties:
     diagProblems:
      type: array
      items:
        type: object
        properties: 
          problem:
            type: object
            properties: 
              probID:
                type: string
                example: "1"
              answerType:
                type: string
              question:
                type: string
              solution:
                type: string
              difficulty:
                type: string
              category:
                type: string
              imgSrc:
                type: string
              timeRecommendation:
                type: string
              creatorID:
                type: string
              createDate:
                type: string
              validatorID:
                type: string
              validateDate:
                type: string
              editorID:
                type: string
              editDate:
                type: string
              source:
                type: string
              intention:
                type: string
              questionInitial:
                type: string
              solutionInitial:
                type: string
              imgsOut:
                type: string

          probChoices:
            type: array
            items:
              type: object
              properties: 
                choiceNum:
                  type: string
                ukID:
                  type: string
                choiceScore:
                  type: string

          probUKRels:
            type: array
            items:
              type: object
              properties:
                ukID:
                  type: string

          diagCurriculum:
            type: object
            properties: 
              curriculumID:
                type: string
              subject:
                type: string
              status:
                type: string
 
  PutDiagProblemDTOIn:
    type: object
    required:
    - userID
    - diagProblems
    properties:
      userID:
        type: string
        example: 'userIDSample'
      diagProblems:
        type: array
        items:
          type: object
          properties:
            problem:
              type: object
              properties: 
                probID:
                  type: string
                  example: "1"
                answerType:
                  type: string
                question:
                  type: string
                solution:
                  type: string
                difficulty:
                  type: string
                category:
                  type: string
                # imgSrc:
                #   type: string
                timeRecommendation:
                  type: string
                # creatorID:
                #   type: string
                # createDate:
                #   type: string
                # validatorID:
                #   type: string
                # validateDate:
                #   type: string
                # editorID:
                #   type: string
                # editDate:
                #   type: string
                source:
                  type: string
                intention:
                  type: string
                questionInitial:
                  type: string
                solutionInitial:
                  type: string
                imgListIn:
                  type: array
                  items:
                    type: string

            probChoices:
              type: array
              items:
                type: object
                properties: 
                  choiceNum:
                    type: string
                  ukID:
                    type: string
                  choiceScore:
                    type: string

            probUKRels:
              type: array
              items:
                type: object
                properties:
                  ukID:
                    type: string

            diagCurriculum:
              type: object
              properties: 
                curriculumID:
                  type: string
                subject:
                  type: string
                status:
                  type: string


                  
  CurriculumList:
    type: object
    required:
    - id
    - chapter
    - section
    - subSection
    - status
    properties:
      id:
        type: integer
        example: 27
      chapter:
        type: string
        example: "성향"
      section:
        type: string
        example: "투자 현황"
      subSection:
        type: string
        example: "보유 주식 수"
      setType:
        type: string
        example: "A"
      subject:
        type: string
        example: "잘못된 기준점에 의한 의사결정 판단"
      status:
        type: string
        example: "출제 보류"
  PartList:
    type: object
    required:
    - id
    - name
    - order
    - count
    properties:
      id:
        type: integer
        example: 3
      name:
        type: string
        example: "파트 3"
      order:
        type: integer
        example: 3
      count:
        type: integer
        example: 4
  SelfProblemIdList:
    type: object
    required:
    - id
    - order
    properties:
      id:
        type: integer
        example: 453
      order:
        type: integer
        example: 3
      difficulty:
        type: string
        example: 중
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /jinhyung_lee/test-studio/1.0.0
schemes:
 - https