swagger: '2.0'
info:
  description: This is an API for test studio.
  version: 1.0.0
  title: test studio API
  contact:
    email: jinhyung_lee@tmax.co.kr
paths:
  /test-studio/uk:
    get:
      tags:
      - teststudio
      summary: get UK list
      description: |
        모든 UK를 가져옵니다.
      produces:
      - application/json
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/UKList'
        400:
          description: bad input parameter
  /test-studio/curriculum:
    get:
      tags:
      - teststudio
      summary: get curriculum list
      description: |
        모든 커리큘럼을 가져옵니다.
      produces:
      - application/json
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/CurriculumList'
        400:
          description: bad input parameter
  /test-studio/curriculum/{id}:
    patch:
      tags:
      - teststudio
      summary: update status of curriculum
      description: |
        커리큘럼의 상태를 수정합니다.
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: part id
        required: true
        type: integer
      - in: body
        name: body
        description: part
        required: true
        schema:
          $ref: '#/definitions/CurriculumPost'
      responses:
        200:
          description: success
        400:
          description: bad input parameter
  /test-studio/part:
    get:
      tags:
      - teststudio
      summary: get part list
      description: |
        모든 파트를 가져옵니다.
      produces:
      - application/json
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/PartList'
        400:
          description: bad input parameter
    post:
      tags:
      - teststudio
      summary: create part
      description: |
        새로운 파트를 저장합니다.
      consumes:
      - application/json
      parameters:
      - in: body
        name: body
        description: part
        required: true
        schema:
          $ref: '#/definitions/PartPost'
      responses:
        200:
          description: success
        400:
          description: bad input parameter
  /test-studio/part/{id}:
    put:
      tags:
      - teststudio
      summary: update part
      description: |
        파트를 수정합니다.
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: part id
        required: true
        type: integer
      - in: body
        name: body
        description: part
        required: true
        schema:
          $ref: '#/definitions/PartPost'
      responses:
        200:
          description: success
        400:
          description: bad input parameter
    delete:
      tags:
      - teststudio
      summary: delete part
      description: |
        파트를 삭제합니다.
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: part id
        required: true
        type: integer
      responses:
        200:
          description: success
        400:
          description: bad input parameter
  /test-studio/problems/self:
    get:
      tags:
      - teststudio
      summary: get self test problem id
      description: |
        커리큘럼에 속한 자가진단 문제들을 가져옵니다.
      produces:
      - application/json
      parameters:
      - in: query
        name: curriculumId
        description: curriculum id
        required: true
        type: integer
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/SelfProblemIdList'
        400:
          description: bad input parameter
  /test-studio/problems/mini:
    get:
      tags:
      - teststudio
      summary: searches mini test problems
      description: |
        필터 조건에 맞는 미니진단 문제들을 정렬하여 가져옵니다.
      produces:
      - application/json
      parameters:
      - in: query
        name: partId
        description: "part id (default : all)"
        required: false
        type: integer
      - in: query
        name: keyword
        description: "search in question, choice, solution, and subject (default: all)"
        required: false
        type: string
      - in: query
        name: order
        description: "order by part, difficulty, status or editDate (default: part name > difficulty > status > edit date)"
        required: false
        type: string
      - in: query
        name: orderOption
        description: ascending or descending
        default: ascending
        type: string
      - in: query
        name: skip
        description: number of records to skip for pagination
        default: 0
        type: integer
        format: int32
        minimum: 0
      - in: query
        name: limit
        description: maximum number of records to return
        default: 20
        type: integer
        format: int32
        minimum: 1
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/MiniProblemList'
        400:
          description: bad input parameter
definitions:
  PartPost:
    type: object
    required:
    - name
    - order
    - count
    properties:
      name:
        type: string
        example: 파트2
      order:
        type: integer
        example: 2
      count:
        type: integer
        example: 4
  MiniProblemList:
    type: object
    properties:
      totalCount:
        type: integer
        example: 132
      totalPage:
        type: integer
        example: 7
      contents:
        $ref: '#/definitions/MiniProblemListContents'
  MiniProblemListContents:
    type: object
    required:
    - id
    - part
    - difficulty
    - subject
    - status
    - question
    - editDate
    properties:
      id:
        type: integer
        example: 62
      part:
        type: string
        example: "파트 1"
      difficulty:
        type: string
        example: "상"
      subject:
        type: string
        example: "잘못된 기준점에 의한 의사결정 판단"
      status:
        type: string
        example: "출제 가능"
      question:
        type: string
        example: "2008년 우리나라 경상수지는 17.5억달러 흑자를 기록하였으며, 실업률은 3.2%
였습니다. 2015년에는 우리나라 경상수지가 1,051.2억달러로 사상최고치를 경
신하였는데 이때 우리나라의 실업률은 몇 %였을까요?"
      editDate:
        type: string
        format: date
        example: 2021.07.27
  UKList:
    type: object
    required:
    - id
    - name
    properties:
      id:
        type: integer
        example: 751
      name:
        type: string
        example: "투자 수익"
  CurriculumList:
    type: object
    required:
    - id
    - chapter
    - section
    - subSection
    - status
    properties:
      id:
        type: integer
        example: 27
      chapter:
        type: string
        example: "성향"
      section:
        type: string
        example: "투자 현황"
      subSection:
        type: string
        example: "보유 주식 수"
      subject:
        type: string
        example: "잘못된 기준점에 의한 의사결정 판단"
      status:
        type: string
        example: "출제 보류"
  PartList:
    type: object
    required:
    - id
    - name
    - order
    - count
    properties:
      id:
        type: integer
        example: 3
      name:
        type: string
        example: "파트 3"
      order:
        type: integer
        example: 3
      count:
        type: integer
        example: 4
  CurriculumPost:
    type: object
    required:
    - status
    properties:
      status:
        type: string
        example: "출제 가능"
  SelfProblemIdList:
    type: object
    required:
    - id
    - order
    properties:
      id:
        type: integer
        example: 453
      order:
        type: integer
        example: 3
      difficulty:
        type: string
        example: 중
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /jinhyung_lee/test-studio/1.0.0
schemes:
 - https